social/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

social/accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

social/groups/models.py
from django.db import models

# Create your models here.

social/posts/models.py
from django.db import models

# Create your models here.

social/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

social/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from . import forms
from django.views.generic import CreateView
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

social/groups/views.py
from django.shortcuts import render

# Create your views here.

social/posts/views.py
from django.shortcuts import render

# Create your views here.

social/social/views.py
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'
    
class HomePage(TemplateView):
    template_name = 'index.html'

social/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

    <div class="container">
        <h1>Log In</h1>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary" value="Login">
        </form>
    </div>

{% endblock %}

social/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

    <div class="container">
        <h1>Sign Up</h1>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary" value="Sign Up">
        </form>
    </div>

{% endblock %}

social/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Social</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Javascript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">

    <!-- Master CSS File -->
    <link rel="stylesheet" href="{% static 'social/css/master.css' %}">

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light mynav" role="navigation" id="navbar">
        <div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Social</a>

            <ul class="navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Groups</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Create Group</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Groups</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mycontent">
        {% block content %}

        {% endblock %}
    </div>
    
</body>
</html>

social/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to Star Social!</h1>
{% endblock %}

social/templates/test.html
{% extends "base.html" %}

{% block content %}
    <h1>You are now logged in!!</h1>

{% endblock %}

social/templates/thanks.html
{% extends "base.html" %}
{% block content %}
    <h1>Thanks for visiting, come back soon!!</h1>
{% endblock %}